# Generated by Django 4.0.2 on 2022-03-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=300, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_buyer_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=300, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_buyer_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('vat_percent', models.FloatField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('net', models.FloatField(blank=True, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_supply', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_issue_date', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.buyer')),
                ('seller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.seller')),
            ],
        ),
    ]
