# Generated by Django 4.0.2 on 2022-03-09 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_buyer_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='organization_name')),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_seller_id', models.CharField(blank=True, max_length=150, null=True)),
                ('organization_name_buyer', models.CharField(blank=True, max_length=300, null=True)),
                ('building_number_buyer', models.IntegerField(blank=True, null=True)),
                ('street_name_buyer', models.CharField(blank=True, max_length=150, null=True)),
                ('district_buyer', models.CharField(blank=True, max_length=150, null=True)),
                ('city_buyer', models.CharField(blank=True, max_length=300, null=True)),
                ('country_buyer', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code_buyer', models.IntegerField(blank=True, null=True)),
                ('additional_number_buyer', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number_buyer', models.IntegerField(blank=True, null=True)),
                ('other_buyer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_supply', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_issue_date', models.DateTimeField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('vat_percent', models.FloatField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_supply', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_number', models.IntegerField(blank=True, default=pos.models.Invoice.number, null=True, unique=True)),
                ('invoice_issue_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name_in_arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=300, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_seller_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('total_vat', models.FloatField(blank=True, null=True)),
                ('total_taxable_amount_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total_amount_due', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('qr', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.setting')),
            ],
        ),
    ]
