# Generated by Django 4.0.2 on 2022-03-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='qr',
        ),
    ]
