# Generated by Django 4.0.2 on 2022-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_pos_description_pos_item_code_pos_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_issue_date',
            field=models.DateTimeField(),
        ),
    ]
