# Generated by Django 4.0.2 on 2022-03-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_invoice_invoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.seller'),
        ),
    ]
