# Generated by Django 4.0.2 on 2022-03-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_buyer_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='pos',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.buyer'),
        ),
        migrations.AddField(
            model_name='pos',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.seller'),
        ),
    ]
