# Generated by Django 4.0.2 on 2022-03-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_rename_product_id_pos_product_remove_buyer_seller_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Setting',
        ),
        migrations.RenameField(
            model_name='pos',
            old_name='seller',
            new_name='setting',
        ),
    ]
