# Generated by Django 4.0.2 on 2022-03-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_rename_seller_setting_rename_seller_pos_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='net',
        ),
    ]
