# Generated by Django 4.0.2 on 2022-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_pos_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
